name: Validate Translations

on:
  pull_request:
    paths:
      - 'translations/**.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Get changed files
      id: changed-files
      run: |
        echo "CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | grep '^translations/.*\.json$' | cut -d'/' -f2 | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_ENV
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Validate translations
      id: validate
      continue-on-error: true
      run: |
        node scripts/validate.js
        echo "exit_code=$?" >> $GITHUB_ENV
        
    - name: Add PR comment
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          let validationResult;
          try {
            validationResult = JSON.parse(fs.readFileSync('validation-results.json', 'utf8'));
          } catch (error) {
            validationResult = { valid: false, errors: ["Could not read validation results"] };
          }
          
          let comment = '## Translation Validation Results\n\n';
          
          if (validationResult.valid) {
            comment += '✅ All checks passed!\n';
            comment += '- Valid JSON format\n';
            comment += '- All required translations present\n';
            comment += '- No extra translations\n';
          } else {
            comment += '❌ Validation failed:\n\n';
            validationResult.errors.forEach(error => {
              comment += `- ${error}\n`;
            });
            comment += '\nPlease fix these issues and update your PR.';
          }
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: comment
          });

    - name: Exit with validation result
      if: always()
      run: exit ${{ env.exit_code }}
