name: Validate Translations

on:
  pull_request:
    paths:
      - 'translations/**.json'
      - 'en_US.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Validate translations
      run: node scripts/validate.js
        
    - name: Add PR comment
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const results = JSON.parse(fs.readFileSync('validation-results.json', 'utf8'));
          
          let comment = '## Translation Validation Results\n\n';
          
          if (results.valid) {
            comment += '✅ All checks passed!\n\n';
          } else {
            comment += '❌ Some checks failed:\n\n';
            results.errors.forEach(error => {
              comment += `- ${error}\n`;
            });
          }
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: comment
          });